### ISSUE TITLE
Error while parsing data. 

### ISSUE THREAD

**Issue by banderLogi** [EmilyBjoerk/lsml#667] opened 2017-03-03 21:28 UTC
When program parsing game data this error occurs:

java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

Program than seems to freeze, using 0 process power, and never finishes loading.

**Comment by EmilyBjoerk** [comment] 2017-03-04 18:32
Duplicate of #666, #665, #664, #663 and #661.

**Closed by EmilyBjoerk** 2017-03-04 18:32 UTC
