### ISSUE TITLE
Hovering mouse cursor over weapon tooltip disappears after a couple of seconds

### ISSUE THREAD

**Issue by thornduck** [EmilyBjoerk/lsml#614] opened 2016-08-03 10:07 UTC
When hovering over weapons in the mechlab, a tooltip appears with detailed information on the weapon or item which is great! However the tooltip disappears after 2 seconds, forcing users to move cursor away and back over the item.

**Comment by EmilyBjoerk** [comment] 2016-08-03 11:50
Duplicate of #533. This issue is blocked until Java 9 later this year.

**Closed** 2016-08-26 06:54 UTC
Labels: bug, duplicate
