### ISSUE TITLE
Feature request: Tool tips need to stay up longer or indefinitely

### ISSUE THREAD

**Issue by LossMentality** [EmilyBjoerk/lsml#651] opened 2017-01-12 02:46 UTC
Great app, one thing is really tough on the user, though.

Some of these tool tips contain a lot of info, and some you want to ponder when looking at (e.g. weapon stats) even after you're done reading. But they disappear way too quickly. Please allow either configurable delay, with option for them to stay until the app receives any form of input, or just default them to stay until input is received.

Note that tool tips sticking around until input is received is fairly common tool-tip behavior.

Get this straightened out, and this becomes MWO mech building's killer app.

Thanks!

I'm editing to ask for even more, This is more work, but tool tips are supposed to be just that: tips. Detailed info should probably not go in a tool tip. It would be nice if when we clicked on any piece of equipment that currently has a tool tip if, instead of a tool tip, the info would show in a dedicated location (e.g. info window located somewhere or have object expand to show text). Waiting for tool tip pop-up when reading stats for multiple objects in a row definietly interrupts the excellent flow you have going.

I realize this involves more work than just extending tool tip time, so I'd be happy to take just that as a first pass, but my second suggestion is much better. In fact, didn't li-song used to do what I just described (i.e. not use tool tip for equipment info)? Or am I not remembering correctly? Maybe it's always been tool tips - I've been away from MWO for over a year, so haven't used li-song since then (like the new look other than this tool-tip issue, though - as always, good job!), but don't remember being so struck by how hard it is to take in large chunks of info and ponder it, though, as I was just now when I first attempted to use this new version.

**Comment by EmilyBjoerk** [comment] 2017-01-12 08:44
Duplicate of #553.

On Jan 12, 2017 03:46, "LossMentality" <notifications@github.com> wrote:

Great app, one thing is really tough on the user, though.

Some of these tool tips contain a lot of info, and some you want to ponder
when looking at (e.g. weapon stats) even after you're done reading. But
they disappear way too quickly. Please allow either configurable delay,
with option for them to stay until the app receives any form of input, or
just default them to stay until input is received.

Note that tool tips sticking around until input is received is fairly
common tool-tip behavior.

Get this straightened out, and this becomes MWO mech building's killer app.

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EmilyBjoerk/lsml/issues/651>, or mute the thread

**Closed** 2017-01-16 15:45 UTC
Labels: duplicate
