### ISSUE TITLE
Mech Lab - Window Exceeds Screen

### ISSUE THREAD

**Issue by crazy6432** [EmilyBjoerk/lsml#521] opened 2016-04-10 19:41 UTC
This is in the 2.0 beta version. When opening an existing 'Mech, or configuring a new 'Mech, the Mechlab window is oversized and extends above and below my screen. There is no way to resize it, and the only way to close it is via the task bar. I cannot see the menu options, but putting my mouse at the very top of the screen will just barely highlight them. I'm using a 1920x1080 monitor.

**Comment by EmilyBjoerk** [comment] 2016-04-10 20:11
Thank you for testing and providing feedback, it is really helpful to me.

I take it this is beta 3 (1.9.9003)? I noticed myself that the mechlab window was a bit large before making the beta 3 version but on the mechs I tried it was still possible to resize it. But it depends on how many quirks/modifiers is on the mech when you open it... >_<; Anywho I *think* that I kinda ninja fixed this in commit f692d918e41ce1972a0061cf0a139129aa12b12e. And I'm not able to reproduce the issue after this fix. 

The fix will be in beta 4 due in a few days.

**Closed by EmilyBjoerk** 2016-04-10 20:11 UTC
Labels: bug
