### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Question2** [EmilyBjoerk/lsml#703] opened 2017-08-07 22:21 UTC
For a long time now, the program has had a memory leak. If you leave it open, it will keep using more and more memory. It shows up as javaw.exe in task manager, seems to use about 700 mb of memory when the program is first opened, but ive seen it use nearly 2gb of memory after leaving it open for a few hours.

**Comment by EmilyBjoerk** [comment] 2017-08-08 07:35
Has the program ever crashed out become unresponsive or slow over time?

Den 8 aug. 2017 00:21 skrev "Question2" <notifications@github.com>:

**Comment by Question2** [comment] 2017-08-09 01:36
No, the program itself doesnt crash, but even when i hit the memory cap, it doesnt seem to free up space. For example, with MWO running, i get a lot more stuttering when LSML is using up tons of memory.

Why is it using more and more memory in the first place, just by sitting there?

Does LSML not use tons of memory when you leave it running for a long time?

**Comment by EmilyBjoerk** [comment] 2017-08-14 07:22
I have 16G of ram and have never had an issue. 

Anyhow, try launching the JAR file directly with for example `java -Xmx1024m -Xms1024m -jar lsml.jar` to limit the Java heap to 1G (the JVM it self will consume a bit more but LSML as an application won't get more.) Find a value for which LSML doesn't crash during normal use (i.e. what it normally needs) and leave it running and see if you get an out of memory exception. If there is no exception then it's the JVM doing it's thing and I really can't do much.

If you still get stuttering then you might want to look into other causes too.

**Comment by Question2** [comment] 2017-08-23 13:34
How do you launch the jar file with that?

**Comment by EmilyBjoerk** [comment] 2017-08-23 15:06
First, make sure that Java is on your system path:
https://java.com/en/download/help/path.xml

(I'm writing this from memory as I don't have access to my computer for a
while to test, please excuse any errors)

Then open a command terminal and cd to where you installed lsml. Then type
`java -Xms512m -Xmx512m  -jar lsml.jar` and that should do it. Also don't
close the terminal or lsml will close too, without saving your garage.

Den 23 aug. 2017 15:34 skrev "Question2" <notifications@github.com>:

**Comment by EmilyBjoerk** [comment] 2017-12-09 20:48
As there has been no reply for 3½ months I'm closing this issue as "can't reproduce".

**Closed by EmilyBjoerk** 2017-12-09 20:48 UTC
