### ISSUE TITLE
error on start up

### ISSUE THREAD

**Issue by nomadwolf991** [EmilyBjoerk/lsml#668] opened 2017-03-07 18:15 UTC
**LSML version:** 2.0.5
**Screen resolutio** 1920x1200
**Java version:** 8uX

**Steps to reproduce issue:**
1. Open LSML

**Actual result:**
tries to load and gives me this error and doesn't open
**Expected result:**
should have opened

java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Comment by XikuKiju** [comment] 2017-03-07 23:56
While this issue seems to be known already there seems to be a fix done. Could you release that? I really would like to continue using the program but cant since no workaround helps for me.

**Comment by EmilyBjoerk** [comment] 2017-03-29 10:07
Duplicate of #667 #666, #665 #664 #663 and #661.

I would prefer if you search before posting please. That way I can spend more time of my time actually working on the fix rather than closing duplicates. 

The fix is in 2.0.6.

**Closed by EmilyBjoerk** 2017-03-29 10:07 UTC
