### ISSUE TITLE
Targeting Computer bonus not applied

### ISSUE THREAD

**Issue by shevanoquam** [EmilyBjoerk/lsml#490] opened 2016-02-17 12:48 UTC
LSML version: 1.7.2
Example issue build (may apply to many)
http://mwo.smurfy-net.de/mechlab#i=280&l=45fc3a3843edc569baeb766fe4c86e21bd4c0683

Steps to reproduce:
1. open lsml
2. Create any kind of new Clan Mech in your garage
3. Fill it up with for example lasers of any kind
4. put in a Targeting Computer
5. Watch the stats on the right corner of the mechlab

Actual result:

Notice, that the ranges for Lasers are still still the same w or w/o Targeting Computer

Expected result:

Statistics should be updated with the bonus parameters the TC gives.

Additional comment: I only tested it with lasers, but it may be the case, that projectile speed, crits etc are also not applied.
Thanks for all the work you put into the project! :)

**Comment by EmilyBjoerk** [comment] 2016-02-17 13:39
Hello and thanks for reporting this issue. 
I'm unable to reproduce the issue, when I add/remove a TC to/from a clan mech, the ranges do update in the offense section of the stats. 

Here's what I do:

1.  Open: [http://t.li-soft.org/?l=rgEYHzIKPBJGDjIKPB4A6zDpWJiSpUqnScVSpUoRfTnlOa2nN8VSpUqnO6dGxMSVKlU%3D](http://t.li-soft.org/?l=rgEYHzIKPBJGDjIKPB4A6zDpWJiSpUqnScVSpUoRfTnlOa2nN8VSpUqnO6dGxMSVKlU%3D).
2. Remove TC 1 from RT.

Actual result: range for alpha/dps and burst changes from 423m to 405m, and range for sustained dps changes from 627m to 600m on the offense panel, as expected.

**Comment by shevanoquam** [comment] 2016-02-17 18:39
Hmm, I'll retest it. I'll let you know about the result. :)

**Comment by EmilyBjoerk** [comment] 2016-02-17 19:25
Okay, thanks for testing again. I will close this issue then.

**Closed by EmilyBjoerk** 2016-02-17 19:25 UTC
Labels: can't reproduce
