### ISSUE TITLE
Error at the start.

### ISSUE THREAD

**Issue by Joker1971** [EmilyBjoerk/lsml#666] opened 2017-03-02 17:40 UTC
**LSML version:** Last
**Screen resolution:** 1920x1200
**Java version:** 8uX
Windows 10

**Steps to reproduce issue:**
1. Open LSML

**Actual result:**
Nothing/something happened

**Expected result:**
Something else should have happened

Error reported:
java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Comment by Weru** [comment] 2017-03-02 18:41
I am having the same problem.
LSML Version 2.0.5
Java Version 8 Update 121
Windows 10 OS

java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Comment by EmilyBjoerk** [comment] 2017-03-02 19:37
Duplicate of #665 #664 #663 and #661. Please search before posting a new issue.

**Closed by EmilyBjoerk** 2017-03-02 19:37 UTC
