### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Question2** [EmilyBjoerk/lsml#436] opened 2015-11-30 12:16 UTC
Is it possible to include the following :

-Tcomp stats (things like crit chance %, velocity increase, etc). It currently only includes range modifiers.

-Include the projectile speed in the weapon stats (when you click on the weapon icons on the left). I know its included in the weapons tab, but that doesnt take into account quirks.

-Include ghost heat for the purpose of cooling efficiency, time to overheat, etc.

-Calculate the seconds to cool down from one alpha's heat, as seconds to cool currently only calculates the seconds to cool down from 100% heat

-Include weapon spread figures for things like LRMs, SRMs, LBX, etc when you click on the weapon icons on the left, so that we can see what the new figures are after being modified by quirks. Same for UAC jam chances.

-Include the Clan ER PPC's splash damage (it's not mentioned anywhere in the program, and the DPH and other stat figures only use the base damage which is misleading)

-Include the crit % bonuse for things like LBX as that doesn't appear to be mentioned anywhere in the program.

-Include the amount of projectiles that clan ACs and UACs fire per burst.

-Include the time needed to clear a UAC jam (i believe it's a flat 5 seconds, might be wrong)

**Comment by EmilyBjoerk** [comment] 2015-12-01 00:24
Most of those can be done. But as I'm working on UI 2.0 I don't want to invest any more time in new features on the old UI. So this will be part of the new UI when I get around to making it.

The clan ER PPC's splash damage is ignored by design and won't change. LSML has as a policy to calculate the damage to the component you're aiming at and the splash is not on that component. This is also why the drop-off from spread is so drastic, it doesn't hit the component you're aiming at. This is what competitive players want to see in my experience. The splash is a "bonus".

I will also not include ghost heat in DPS numbers because it depends on firing pattern and which weapons are used/grouped. For example 6 slas + 6 mlas will trigger massive ghost heat on first shot but not on second round of shots because their cooldowns are different (SLAS will fire first, then MLAS without ghost heat). The DPS is calculated assuming the pilot knows how to avoid triggering ghost heat by staggering shots by 0.5s. It is simply too much work to get this right for all players and cases.

**Comment by EmilyBjoerk** [comment] 2015-12-10 22:19
This will be implemented by #446. I'm closing this issue for now.

**Closed by EmilyBjoerk** 2015-12-10 22:19 UTC
Labels: enhancement
