### ISSUE TITLE
Java error - LSML 2.0.5

### ISSUE THREAD

**Issue by Weru** [EmilyBjoerk/lsml#665] opened 2017-02-28 19:43 UTC
**LSML version:**  2.0.5
**Screen resolution:** 1920x1200
**Java version:** 8 update 121

**Steps to reproduce issue:**
1. Open LSML; Title window stays stuck on "Parsing  Game Data" and produces error window.
Error:
java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
2. Unable to progress past this point.

** I have tried uninstalling and reinstalling LSML and Java.  This resulted in no additional progress to running the program.
** I deleted my LSML Garage and allowed LSML to recreate it.  The program then had the same error as listed above.  
** I'm not sure what else to try to get the program operating.

**Comment by xtacinside** [comment] 2017-03-01 11:25
same problem!!! signed to github for this

**Comment by EmilyBjoerk** [comment] 2017-03-01 19:27
Duplicate of #664, #663 and #661.

**Closed by EmilyBjoerk** 2017-03-01 19:27 UTC
