### ISSUE TITLE
Flashing Window

### ISSUE THREAD

**Issue by AkulaOsis** [EmilyBjoerk/lsml#380] opened 2014-12-16 02:15 UTC
Using latest Beta version, not the good type of flashing. Flashes black and comes back very quickly, did the normal troubleshooting. Upgraded Java, new video drivers and reinstalled Directx.

Thanks in advance for this great program.

**Comment by LiSongMWO** [comment] 2014-12-16 09:40
I do not understand what happens, can describe in more detail and give me
steps to reproduce? Also try updating to the latest version.

**Comment by EmilyBjoerk** [comment] 2015-02-01 11:54
I'm unable to reproduce the issue. I cannot see any kind of flashing in LSML. This is most likely an issue with your Java installation or graphics driver or some interfering program. 

If no further information is provided before the 1st of March, I will assume that the issue has resolved itself and close the ticket.

**Comment by EmilyBjoerk** [comment] 2015-02-22 16:16
Final call, Sunday next week I will close the issue if no further information is provided.

**Comment by AkulaOsis** [comment] 2015-03-03 16:21
Li Song,
Thank you, please close this as I have moved the application to my laptop instead of my gaming computer. Seyla,

Thibideau Osis
Theta Galaxy - Smoke Adders
Expeditionary Force of Clan Star Adder

**Closed** 2015-04-11 19:12 UTC
Labels: can't reproduce
