### ISSUE TITLE
Store the collapsed / expanded state of the side bar categories between sessions

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#658] opened 2017-01-25 09:03 UTC
I am routinely collapsing the Efiiciencies and Quirks groups so that the rest actually fits the screen. I also never use the Armor Wizard, but I do use the Mobility view to look at my top speed. Can't you save this state so that my last choice of visible and collapsed categories is respected?

**Comment by EmilyBjoerk** [comment] 2017-01-26 14:18
Duplicate of #608. Patches are welcome.

**Closed by EmilyBjoerk** 2017-01-26 14:18 UTC
Labels: duplicate

**Comment by VioletGiraffe** [comment] 2017-01-26 14:20
Oops, really sorry for posting a dupe.

**Comment by EmilyBjoerk** [comment] 2017-01-26 14:22
No worries.
