### ISSUE TITLE
V2.0.5 64Bit Unexpected Error

### ISSUE THREAD

**Issue by Weru** [EmilyBjoerk/lsml#664] opened 2017-02-26 13:31 UTC
**LSML version:** 2.0.5 64bit
**Screen resolution:** 1920x1200
**Java version:** 8uX

**Steps to reproduce issue:**
1. Open LSML
2. Click on nothing (happens on load)
3. Then look at the popup
4. Finally do this, sigh and post the error

**Actual result:**
java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Expected result:**
No error popup

**Comment by NavidA1** [comment] 2017-02-26 22:50
Having the same issue.

Can't open LSML due to the error mentioned above.

I'm using the 64bit version.

**Comment by BT-JMP** [comment] 2017-02-27 03:06
Confirmed. Same issue, 64-bit.

**Comment by XikuKiju** [comment] 2017-02-27 11:06
Having the same at 32bit

**Comment by EmilyBjoerk** [comment] 2017-02-27 11:41
Duplicate of #661.

**Closed by EmilyBjoerk** 2017-02-27 11:41 UTC
