### ISSUE TITLE
New loadouts cannot be renamed

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#669] opened 2017-03-16 17:25 UTC
1. Create a new loadout, doesn't matter which mech.
2. Press the pencil button to edit its name.
3. Change at least 1 symbol in the name and press Enter to save.
4. Observe the informative message:

![image](https://cloud.githubusercontent.com/assets/1175926/24009654/47ab3c32-0a7e-11e7-94c0-9c03616cb30a.png)

followed by

![image](https://cloud.githubusercontent.com/assets/1175926/24009662/4f7d1854-0a7e-11e7-9e7a-75e8c55fb862.png)

5. The name reverts to its original.

**Comment by Smokey2** [comment] 2017-03-21 14:16
Same problem here. A work around is to save it as the default name then rename it from the Loadouts screen.

**Comment by VioletGiraffe** [comment] 2017-07-25 07:05
Still occurs in 2.0.7, is that as intended? As in, didn't this changeset make it into 2.0.7?

**Comment by EmilyBjoerk** [comment] 2017-07-25 11:33
Darn it, I thought I fixed that...

**Comment by VioletGiraffe** [comment] 2017-07-25 11:34
I know the feeling :)
Perhaps, add a test when you have the time?..

**Comment by EmilyBjoerk** [comment] 2017-07-25 11:38
I don't have UI tests yet and it's too much work for me to get it set up at this point. I would love it if some one would contribute some UI tests though :wink: .

**Comment by VioletGiraffe** [comment] 2017-07-25 11:44
Ah, fair enough (I never know how to test UI, so don't look at me). I just thought that this issue is not actually _in_ the UI, so it could perhaps be tested. Never mind.

**Comment by EmilyBjoerk** [comment] 2017-08-03 10:47
I'm unable to reproduce this in `develop`  although I have no recollection of doing anything to fix it.

There should be no way it is possible for the patchset to not have made its way to the release so I don't really know what happened. As I'm fairly certain that I re-confirmed the issue on `develop` but now I can't reproduce it. Maybe it was another error that just looked like this error, and I fixed the cause in some other issue, I don't know. 

For now it works as it should in develop so I'll close the issue again. Feel free to re-open if the issue re-appears in 2.0.8 or later (or `develop`).

**Closed by EmilyBjoerk** 2017-08-03 10:47 UTC
Labels: bug
