### ISSUE TITLE
Steam Install is not found

### ISSUE THREAD

**Issue by WarWolfen** [EmilyBjoerk/lsml#509] opened 2016-04-04 22:30 UTC
Just like the issue in the old version, my Steam-based installation of MWO is not found during install.

**Comment by EmilyBjoerk** [comment] 2016-04-05 07:14
Hmm that's odd. I thought I fixed that...

What version is this?

Where is the install located? Can you screenshot the contents of the
install directory and sub directories to me?

**Comment by WarWolfen** [comment] 2016-04-05 07:18
Greetings!

I will, if I am back at the Computer in question. That will be not for tonight 9:00 pm CEST.

**Comment by WarWolfen** [comment] 2016-04-06 18:57
Greetings,
Installation is installed here:
D:\Spiele\SteamLibrary\steamapps\common\MechWarrior Online\Bin64

Latest version of:
- Windows 10
- Steam
- MWO

It is not clear to me where the version of LSML is to be seen...
![mwo_client](https://cloud.githubusercontent.com/assets/16292643/14329114/3372ecc2-fc3a-11e5-8514-1912e5a52e59.png)

**Comment by WarWolfen** [comment] 2016-04-06 18:58
Need any other screens?

**Comment by EmilyBjoerk** [comment] 2016-04-06 19:40
That's fine thank you, I think you have the 2.0 pre-release. And I found the cause (the fix I did for 1.7.2 didn't make it into 2.0 so I'll just pull it in).

**Comment by EmilyBjoerk** [comment] 2016-04-06 21:02
Should be fixed by commit 06c2de5

**Closed** 2016-04-06 21:02 UTC
Labels: bug
