### ISSUE TITLE
Mech icons

### ISSUE THREAD

**Issue by anonymous555** [EmilyBjoerk/lsml#398] opened 2015-05-27 23:42 UTC
Hi:

Mech icons can be obtained here

http://static.mwomercs.com/api/assets/mechicons/kfx-s.png

Also larger icons are available here

http://static.mwomercs.com/img/theme/battlemechs/

For all the mechs by name.

It would be really nice to see a mech icon in lsml.

**Comment by EmilyBjoerk** [comment] 2015-06-06 09:53
Ah nice I didn't know about those links. This issue is related to/duplicate of #387 but those links make it more feasible to implement.

**Comment by EmilyBjoerk** [comment] 2016-11-11 15:16
I have decided against adding icons to LSML. I feel that they will not play well with the current graphical idoms used in LSML that are monochrome and simplistic while in game icons would be colour and not simplistic. For that reason I'm closing this issue.

**Closed by EmilyBjoerk** 2016-11-11 15:16 UTC
Labels: enhancement
