### ISSUE TITLE
IS/Clan filters not working

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#591] opened 2016-07-10 23:31 UTC
Don't know if it just a problem on my machine, but unchecking the IS/Clan filters in the lower left corner of the UI doesn't do anything - the list always shows Mechs from both categories.

Anyone else having that problem?

**Comment by EmilyBjoerk** [comment] 2016-07-12 05:22
What view are they not working on?
On 11 Jul 2016 01:31, "Zesaric" <notifications@github.com> wrote:

Don't know if it just a problem on my machine, but unchecking the IS/Clan
filters in the lower left corner of the UI doesn't do anything - the list
always shows Mechs from both categories.

Anyone else having that problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EmilyBjoerk/lsml/issues/591>, or mute the thread
<https://github.com/notifications/unsubscribe/AFD6MVxwPuRvTENK6REpIc3cwBEu3VOOks5qUYDGgaJpZM4JI8W3>
.

**Comment by Zesaric** [comment] 2016-07-12 19:57
I mostly use the "Large List" view but they aren't working in "Small List" view either.

**Comment by EmilyBjoerk** [comment] 2016-07-12 20:57
Do you mean under "View loadouts"? If so they are not supposed to affect
your garage as it may wrongly lead you to believe that your garage has been
corrupted.

**Comment by Zesaric** [comment] 2016-07-12 21:13
Ah I see!!! :-)

Indeed, I meant under "Loadouts" but now I realize the filter is only supposed to work in "Chassis". The placement in the left navigation led me to believe it was supposed to whatever view is chosen in the right pane.

So that might be the the only suggestion then to maybe place the filter directly next to "List of all chassis", so it is clear that it only applies to that view.

Otherwise the issue is resolved with "user" being the source of the error! ;-)

**Comment by EmilyBjoerk** [comment] 2016-07-12 21:15
It will affect chassis and payload graph and weapon list though.

**Comment by Zesaric** [comment] 2016-07-12 21:24
Ah ok, that makes sense. Thanks for the additional info! :-)

**Comment by EmilyBjoerk** [comment] 2016-07-13 10:29
Superseded by #594. Closing this issue as the filters are working as intended but the intentions is not the best.

**Closed by EmilyBjoerk** 2016-07-13 10:29 UTC
